[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/cli",
  "crates/util",
  "crates/language",
  "crates/gritmodule",
  "crates/gritcache",
  "crates/auth",
  "crates/externals",
  "crates/wasm-bindings",
  "crates/marzano_messenger", "crates/cli_bin",
]
exclude = [
  "resources",
  "vendor/web-tree-sitter",
  "vendor/tree-sitter-facade",
]

[workspace.dependencies]
ai_builtins = { git = "https://github.com/getgrit/ai_builtins.git" }
anyhow = "1.0.70"
assert_cmd = "2.0.12"
base64 = "0.21.2"
buildkite-test-collector = "0.1.1"
cc = "1.0"
chrono = "0.4.26"
clap = "4.1.13"
clap-markdown = { git = "https://github.com/getgrit/clap-markdown" }
cli_server = { git = "https://github.com/getgrit/cli_server.git" }
colored = "2.0.4"
console = "0.15.7"
console_error_panic_hook = "0.1.7"
dashmap = "5.5.3"
derive_builder = "0.13.1"
dialoguer = "0.10.4"
elsa = "1.9.0"
embeddings = { git = "https://github.com/getgrit/embeddings.git" }
enum_dispatch = "0.3.12"
env_logger = "0.10.0"
extism = "1.0.0-rc7"
flate2 = { version = "1.0.17", default-features = false }
fs_extra = "1.3"
futures = "0.3.29"
getrandom = "0.2.11"
git2 = { version = "0.17.2", default-features = false }
homedir = "0.2.1"
http = "0.2.11"
ignore = "0.4.21"
im = "15.1.0"
indicatif = "0.17.5"
indicatif-log-bridge = "0.2.1"
insta = "1.30.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.20"
markdown = "1.0.0-alpha.11"
ntest = "0.9.0"
openssl = "0.10"
opentelemetry = "0.21.0"
opentelemetry-otlp = "0.14.0"
opentelemetry_sdk = "0.21.1"
path-absolutize = "3.1.1"
predicates = "3.0.3"
rand = "0.8.5"
rayon = "1.8.0"
regex = "1.7.3"
reqwest = "0.11.22"
# Do *NOT* upgrade beyond 1.0.171 until https://github.com/serde-rs/serde/issues/2538 is fixed
serde = "1.0.164"
serde-wasm-bindgen = "0.6"
serde_json = "1.0.114"
serde_yaml = "0.9.25"
sha2 = "0.10.8"
similar = "2.2.1"
tempfile = "3.8.1"
tokio = "1.35.1"
tower = "0.4.13"
tower-lsp = "0.20.0"
tracing = { version = "0.1.40", default-features = false }
tracing-opentelemetry = { version = "0.22.0", default-features = false }
tree-sitter = "~0.20.10"
tree-sitter-traversal = { version = "0.1.2", default-features = false }
trim-margin = "0.1.0"
uuid = "1.1"
walkdir = "2.3.3"
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
wasm-bindgen-test = "0.3.39"
web-sys = "0.3.66"
