[package]
name = "marzano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
marzano-cli = { path = "../cli", default-features = false }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1.40", default-features = false }

[features]

grit_tracing = [
  "marzano-cli/grit_tracing",
]